export const ADD_ERROR = 'ADD_ERROR';
export const CLEAN_ERRORS = 'CLEAN_ERRORS';

export const STABLE_IOS_BROWSER_HEIGHT = 'STABLE_IOS_BROWSER_HEIGHT';

export const RECORD_DEVICE_TYPE = 'RECORD_DEVICE_TYPE';
