export const PLACES_AUTOCOMPLETE_REQUEST_START =
  'PLACES_AUTOCOMPLETE_REQUEST_START';
export const PLACES_AUTOCOMPLETE_REQUEST_SUCCESS =
  'PLACES_AUTOCOMPLETE_REQUEST_SUCCESS';
export const PLACES_AUTOCOMPLETE_REQUEST_ERROR =
  'PLACES_AUTOCOMPLETE_REQUEST_ERROR';
export const CLEAN_SUGGESTIONS = 'CLEAN_SUGGESTIONS';
export const SELECT_PLACE = 'SELECT_PLACE';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_START = 'FETCH_WEATHER_START';
export const FETCH_WEATHER_ERROR = 'FETCH_WEATHER_ERROR';
export const GET_PLACE_DETAILS_REQUEST_START =
  'GET_PLACE_DETAILS_REQUEST_START';
export const GET_PLACE_DETAILS_REQUEST_SUCCESS =
  'GET_PLACE_DETAILS_REQUEST_SUCCESS';
export const GET_PLACE_DETAILS_REQUEST_ERROR =
  'GET_PLACE_DETAILS_REQUEST_ERROR';
export const SAVE_PLACE = 'SAVE_PLACE';
export const REMOVE_PLACE = 'REMOVE_PLACE';
export const SWITCH_LIST_OPEN_STATE = 'SWITCH_LIST_OPEN_STATE';
export const MOBILE_BROWSER_BARS_FIXER = 'MOBILE_BROWSER_BARS_FIXER';
export const RECORD_BROWSER = 'RECORD_BROWSER';
export const RECORD_DEVICE_TYPE = 'RECORD_DEVICE_TYPE';
export const GOOGLE_API_LOAD = 'GOOGLE_API_LOAD';
