export const SELECT_PLACE = 'SELECT_PLACE';
export const REMOVE_PLACE = 'REMOVE_PLACE';
export const SAVE_PLACE = 'SAVE_PLACE';
export const UNSELECT_PLACE = 'UNSELECT_PLACE';
export const SWITCH_LIST_OPEN_STATE = 'SWITCH_LIST_OPEN_STATE';
export const PLACE_DETAILS_REQUEST_SUCCESS = 'PLACE_DETAILS_REQUEST_SUCCESS';
