export const REQUEST_SUGGESTIONS_PLACES_START =
  'REQUEST_SUGGESTIONS_PLACES_START';
export const REQUEST_SUGGESTIONS_PLACES_SUCCESS =
  'REQUEST_SUGGESTIONS_PLACES_SUCCESS';
export const SELECT_SUGGESTION_PLACE = 'SELECT_SUGGESTION_PLACE';
export const CLEAN_SUGGESTIONS = 'CLEAN_SUGGESTIONS';

