export const LOAD_GOOGLE_MAPS_API_START = 'LOAD_GOOGLE_MAPS_API_START';
export const LOAD_GOOGLE_MAPS_API_SUCCESS = 'LOAD_GOOGLE_MAPS_API_SUCCESS';
export const LOAD_GOOGLE_MAPS_API_ERROR = 'LOAD_GOOGLE_MAPS_API_ERROR';

export const INIT_GOOGLE_PLACES_SERVICE_START =
  'INIT_GOOGLE_PLACES_SERVICE_START';
export const INIT_GOOGLE_PLACES_SERVICE_SUCCESS =
  'INIT_GOOGLE_PLACES_SERVICE_SUCCESS';
export const INIT_GOOGLE_PLACES_SERVICE_ERROR =
  'INIT_GOOGLE_PLACES_SERVICE_ERROR';

export const INIT_GOOGLE_AUTOCOMPLETE_SERVICE_START =
  'INIT_GOOGLE_AUTOCOMPLETE_SERVICE_START';
export const INIT_GOOGLE_AUTOCOMPLETE_SERVICE_SUCCESS =
  'INIT_GOOGLE_AUTOCOMPLETE_SERVICE_SUCCESS';
export const INIT_GOOGLE_AUTOCOMPLETE_SERVICE_ERROR =
  'INIT_GOOGLE_AUTOCOMPLETE_SERVICE_ERROR';

export const PLACES_AUTOCOMPLETE_REQUEST_START =
  'PLACES_AUTOCOMPLETE_REQUEST_START';
export const PLACES_AUTOCOMPLETE_REQUEST_SUCCESS =
  'PLACES_AUTOCOMPLETE_REQUEST_SUCCESS';
export const PLACES_AUTOCOMPLETE_REQUEST_ERROR =
  'PLACES_AUTOCOMPLETE_REQUEST_ERROR';

export const PLACE_DETAILS_REQUEST_START = 'PLACE_DETAILS_REQUEST_START';
export const PLACE_DETAILS_REQUEST_SUCCESS = 'PLACE_DETAILS_REQUEST_SUCCESS';
export const PLACE_DETAILS_REQUEST_ERROR = 'PLACE_DETAILS_REQUEST_ERROR';
